name: 抢购多点优惠券任务1
on:
  push:
    branches: [ master ]
  schedule:
    # 定时任务，在每天的16点执行任务/01点/02点
    - cron: '55 15 * * *'
    - cron: '55 1 * * *'
    - cron: '55 2 * * *'
jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: clone script
        run: wget http://49.233.24.188/assets/dd_client.py -O /tmp/dd_client.py
      - name: execute script
        run: python3 /tmp/dd_client.py 1 
