name: 抢购多点优惠券任务九点-10-2
on:
  push:
    branches: [ master ]
  schedule:
    # 定时任务，在每天的16点执行任务/01点/02点
    - cron: '54 15 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: clone script
        run: wget http://49.233.24.188/assets/dd_client2.py -O /tmp/dd_client2.py
      - name: execute script
        run: python3 /tmp/dd_client2.py 10 
